setOnActuator(scrivo(gameManager(gameManager(x(X))))):-
setOnActuator(scrivo(gameManager(gameManager(y(X))))):-
setOnActuator(scrivo(gameManager(gameManager(x2(X))))):-
setOnActuator(scrivo(gameManager(gameManager(y2(X))))):-
%random(random(randomDirection(dir(X)))).
%read(griglia(griglia(player(x(X))))).
%read(griglia(griglia(player(y(X))))).
%read(griglia(griglia(player(val(X))))).
%read(griglia(griglia(player(ch(X))))).
%read(griglia(griglia(direzionePrecedente(X)))).
%read(griglia(griglia(direzione(X)))).
%read(griglia(griglia(mappa(X,cella(x(V)))))).
%read(griglia(griglia(mappa(X,cella(y(V)))))).
%read(griglia(griglia(mappa(X,cella(val(V)))))).
%read(griglia(griglia(mappa(X,cella(ch(V)))))).
